  master[m
  multichannel_images_arif[m
* [32mtool_installation_arif[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/auto_threshold_addition[m
  [31mremotes/origin/barcelona2024[m
  [31mremotes/origin/chunked_pyramidal_image_storage.md[m
  [31mremotes/origin/copilot/fix-convolutional-filters-activities[m
  [31mremotes/origin/diffractionLimit[m
  [31mremotes/origin/exercise_preface[m
  [31mremotes/origin/fix_filter_stats_variance[m
  [31mremotes/origin/granulometry[m
  [31mremotes/origin/hessianShapeAnalysis[m
  [31mremotes/origin/issue610[m
  [31mremotes/origin/issue659[m
  [31mremotes/origin/issue_584[m
  [31mremotes/origin/japan[m
  [31mremotes/origin/master[m
  [31mremotes/origin/measure_intensties_rois[m
  [31mremotes/origin/microscopy[m
  [31mremotes/origin/mobieCLEM[m
  [31mremotes/origin/multichannel_images_arif[m
  [31mremotes/origin/nbh_filters_python[m
  [31mremotes/origin/new_module_layout[m
  [31mremotes/origin/python_image_file_formats[m
  [31mremotes/origin/python_load_from_url[m
  [31mremotes/origin/refactor_tiff_zarr[m
  [31mremotes/origin/show-courses[m
  [31mremotes/origin/spatial_calibration_tif_python_image[m
  [31mremotes/origin/splitting_slice_viewing[m
  [31mremotes/origin/tiff[m
  [31mremotes/origin/tool_installation_arif[m
  [31mremotes/origin/update_datatypes_bioio[m
  [31mremotes/origin/update_projections_bioio[m
  [31mremotes/origin/user_input[m
  [31mremotes/origin/workflow_quantitative_image_inspection[m
